package com.deployforge.deployment.pipeline.steps;

import com.deployforge.common.util.SafePaths;
import com.deployforge.config.DeployForgeProperties;
import com.deployforge.deployment.DeploymentStateService;
import com.deployforge.deployment.DeploymentStepName;
import com.deployforge.deployment.pipeline.DeploymentContext;
import com.deployforge.deployment.pipeline.PipelineLogSink;
import com.deployforge.deployment.pipeline.PipelineStep;
import com.deployforge.deployment.pipeline.StepCancelledException;
import com.deployforge.deployment.pipeline.StepFailedException;
import com.deployforge.git.GitCloneException;
import com.deployforge.git.GitCloneService;
import com.deployforge.log.DeploymentLogService;
import com.deployforge.log.LogSource;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 * Clones the repository into an isolated working directory.
 *
 * <p>Layout: {@code <deployment root>/<deploymentId>/source}. The deployment id is a UUID generated by
 * the platform, never user input, and every subsequent path join is validated by
 * {@link SafePaths#resolveInside} so a crafted root directory cannot escape the build tree.
 */
@Component
public class CloneRepositoryStep implements PipelineStep {

    private static final Logger log = LoggerFactory.getLogger(CloneRepositoryStep.class);

    private final GitCloneService cloneService;
    private final DeploymentLogService logService;
    private final DeploymentStateService stateService;
    private final DeployForgeProperties properties;

    public CloneRepositoryStep(
            GitCloneService cloneService,
            DeploymentLogService logService,
            DeploymentStateService stateService,
            DeployForgeProperties properties) {
        this.cloneService = cloneService;
        this.logService = logService;
        this.stateService = stateService;
        this.properties = properties;
    }

    @Override
    public DeploymentStepName name() {
        return DeploymentStepName.CLONE;
    }

    @Override
    public boolean applies(DeploymentContext context) {
        return !context.isImageReuse();
    }

    @Override
    public String skipReason(DeploymentContext context) {
        return "Reusing the image from deployment #" + context.getDeploymentNumber() + " source";
    }

    @Override
    public void execute(DeploymentContext context) {
        Path root = Path.of(properties.deployment().rootPath()).toAbsolutePath().normalize();
        Path workDirectory = SafePaths.resolveInside(root, context.getDeploymentId().toString());
        Path sourceDirectory = SafePaths.resolveInside(workDirectory, "source");

        try {
            SafePaths.createDirectories(workDirectory);
            // A leftover directory from a retried deployment would make JGit refuse to clone.
            SafePaths.deleteQuietly(sourceDirectory);
            Files.createDirectories(sourceDirectory);
        } catch (IOException e) {
            throw new StepFailedException(
                    "Could not prepare the build directory: " + e.getMessage(),
                    "Check that DEPLOYMENT_ROOT_PATH exists and is writable by the DeployForge process.",
                    null,
                    e);
        }

        context.setWorkDirectory(workDirectory);
        context.setSourceDirectory(sourceDirectory);

        logService.append(
                context.getDeploymentId(),
                com.deployforge.log.LogLevel.INFO,
                LogSource.GIT,
                "Cloning "
                        + context.repositoryFullName()
                        + " on branch "
                        + context.getBranch()
                        + (context.isRepositoryPrivate() ? " (private)" : ""));

        PipelineLogSink sink =
                new PipelineLogSink(
                        logService, context.getDeploymentId(), LogSource.GIT, context::isCancelled, false);

        if (context.isRepositoryPrivate() && context.getGithubToken() == null) {
            throw new StepFailedException(
                    "This repository is private and no usable GitHub token is available.",
                    "Sign in with GitHub again and grant the 'repo' scope, then redeploy.");
        }

        try {
            GitCloneService.CloneResult result =
                    cloneService.clone(
                            new GitCloneService.CloneRequest(
                                    context.getCloneUrl(),
                                    context.getBranch(),
                                    context.getGithubToken(),
                                    sourceDirectory,
                                    properties.deployment().cloneTimeout(),
                                    sink));

            context.setCommitSha(result.commitSha());
            context.setCommitMessage(result.commitMessage());
            context.setCommitAuthor(result.commitAuthor());
            stateService.recordCommit(
                    context.getDeploymentId(),
                    result.commitSha(),
                    result.commitMessage(),
                    result.commitAuthor());

            logService.append(
                    context.getDeploymentId(),
                    com.deployforge.log.LogLevel.INFO,
                    LogSource.GIT,
                    "Repository cloned at commit "
                            + result.commitSha().substring(0, 7)
                            + " - \""
                            + result.commitMessage()
                            + "\"");

        } catch (GitCloneException e) {
            if (e.isCancelled()) {
                throw new StepCancelledException("Clone cancelled");
            }
            log.warn(
                    "clone_failed deployment={} repository={} reason={}",
                    context.getDeploymentId(),
                    context.repositoryFullName(),
                    e.getMessage());
            throw new StepFailedException(
                    e.getMessage(),
                    e.isAuthenticationFailure()
                            ? "Reconnect GitHub from Account settings, then redeploy."
                            : "Verify the branch still exists and that DeployForge has access to the repository.");
        } finally {
            sink.flush();
            // The token has served its only purpose; do not carry it through the rest of the pipeline.
            context.clearGithubToken();
        }
    }
}
