package com.deployforge.activity;

/** Vocabulary of the activity feed. Kept as an enum so the UI can map each one to an icon. */
public enum ActivityAction {
    PROJECT_IMPORTED,
    PROJECT_UPDATED,
    PROJECT_DELETED,
    PROJECT_ARCHIVED,

    ENVIRONMENT_CREATED,
    ENVIRONMENT_UPDATED,
    ENVIRONMENT_DELETED,

    VARIABLE_CREATED,
    VARIABLE_UPDATED,
    VARIABLE_DELETED,
    VARIABLES_BULK_UPDATED,

    DEPLOYMENT_CREATED,
    DEPLOYMENT_SUCCEEDED,
    DEPLOYMENT_FAILED,
    DEPLOYMENT_CANCELLED,
    DEPLOYMENT_ROLLED_BACK,
    DEPLOYMENT_PROMOTED,

    AUTO_DEPLOY_TRIGGERED,
    AI_ANALYSIS_COMPLETED,

    MEMBER_ADDED,
    MEMBER_ROLE_CHANGED,
    MEMBER_REMOVED
}
